#!/bin/bash
step=1
wait=1
state_1=1
state_2=0
state_3=1
function help_screen () {
  echo "command [type] url [options]"
  echo "    -h for this screen"
  echo "types are:"
  echo "    -c check connection to internet"
  echo "    -w watch interface"
  echo "    -r reset interface"
  echo "    -a show ip adress"
  echo "    -s sync date/time"
  echo ""
  exit 0;}
function check {
  # test internet connection if any
    # starts output with time of execution
    o=$(date +%k:%M:%S)
    # attempt to connect to google.com
    echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1""
    check_1="$?"
    case "$check_1" in
      0)
        o+=" - C1:Internet"
        ;;
      1)
        o+=" - C1:No Internet"
        ;;
      2)
        o+=" - C1:No Connection"
        ;;
    esac #case $check in
    curl --silent --head http://www.google.com/ |egrep '20[0-9] Found|30[0-9] Found' > /dev/null
    check_2="$?"
    case "$check_2" in
      0)
        o+=" - C2:No Internet"
        ;;
      1)
        o+=" - C2:Internet"
        ;;
      2)
        o+=" - C2:No Connection"
        ;;
    esac #case $check in
    echo $o;}

function watch {
# log network conection and internet connection
  while true; do
    # starts output with time of execution
    o=$(date +%k:%M:%S)
    # checking any interfaces exist
    if [[ $(ls /sys/class/net/ | grep -v lo) != null ]]; then
      o+=" - Interface present"
      # checking provided interface for connection
      check_2="$(cat /sys/class/net/$interface/carrier)"
      case $check_2 in
          0)
            o+=" - C2:disconnected"
            ;;
          1)
            o+=" - C2:Connected"
            ;;
      esac # case $check_2 in
      if [ $check_2 != $state_1 ]; then
        step=0
        wait=1
      fi #if [ $check_2 != $state_1 ]; then
      # saving check_2 for next loop
      state_1=$check_2
      # check 3
      if [ $check_2 != "0" ]; then
        echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1""
        check_3="$?"
        case $check_3 in
          0)
            o+=" - C3:Internet"
            ;;
          1)
            o+=" - C3:No Internet"
            ;;
          2)
            o+=" - C3:No Connection"
            ;;
        esac #case $state_2 in
        if [ ! $check_3 -eq $state_2 ]; then
          step=0
          wait=1
        fi #if [ ! $check_3 -eq $state_2 ]; then
        # saving check_3 for next loop
        state_2=$check_3
        # starting check 2
        if [ $check_3 = "0" ]; then
          curl --silent --head http://www.google.com/ |egrep '20[0-9] Found|30[0-9] Found' > /dev/null
          check_4="$?"
          case "$check_4" in
            0)
              o+=" - C4:No Internet"
              ;;
            1)
              o+=" - C4:Internet"
              ;;
            2)
              o+=" - C4:No Connection"
              ;;
          esac #case $check in
          if [ ! $check_4 -eq $state_3 ]; then
            step=0
            wait=1
          fi #if [ ! $check_2 -eq $state_2 ]; then
          # saving check_4 for next loop
          state_3=$check_4
        fi #if [ $check_3 = "0" ]; then
      fi #if [ $check_2 != "0" ]; then
      #printing results
      echo $o
      interval
    else #if [[ $(ls /sys/class/net/ | grep -v lo) != null ]]; then
      o+=" - No Interfaces"
      read -p "Hit ENTER when interfaces are present" ; echo 
    fi #if [[ $(ls /sys/class/net/ | grep -v lo) != null ]]; then
  done #while true; do
  }

function reset {
  network="$(nmcli dev)"
  network="${network#*$interface}"
  network="${network%%[[:cntrl:]]*}"
  network="${network% *}"
  network="${network##*  }"
  echo "network:$network"
  nmcli con down "$network"
  sleep 10s
  result="starting"
  while [ ! $result = "0" ]; do
    step=0
    wait=5
    interval
    echo "atempting reconection"
    nmcli con up "$network"
    result=$?
  done
  }

function interval {
  ((step ++)) #iterating count
  case $wait in
    1) #seconds of sleep per step
      if [ "$step" = 60 ];then #check every second for a minute*
        wait=5
        step=1
      fi #if step
    ;;
    5) #seconds of sleep per step
      if [ "$step" = 60 ];then #check every 5 second for 5 minute*
        wait=30
        step=1
      fi #if step
    ;;
    #~ 30) #seconds of sleep per step
      #~ if [ "$step" = 8 ];then  #check every 30 seconds for 4 minute*
        #~ wait=60
        #~ step=1
      #~ fi #if step
    #~ ;;
    #* time inbetween waits is "time set" plus "execution time"
  esac
  read -t $wait -p "Hit ENTER or wait $wait seconds"; echo; echo
  #sleep "$wait"
  }

while getopts ":hcw:r:as" opt; do
  case $opt in
    h)
      help_screen
      exit 0
      ;;
    c)
      check
      ;;
    w)
      declare -r interface="${OPTARG}"
      watch
      exit 0
      ;;
    r)
      declare -r interface="${OPTARG}"
      reset
      ;;
    a)
      #~ echo $(dig +short myip.opendns.com @resolver1.opendns.com)
      echo $(curl icanhazip.com)
      exit 0
      ;;
    s)
      ntpdate -q 0.fedora.pool.ntp.org
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      help_screen
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      help_screen
      exit 1
      ;;
  esac #case $opt in
done #while getopts "" opt; do

## notes
#~ $ date ; read -t 10 -p "Hit ENTER or wait ten seconds" ; echo ; date
#~ Tue Feb 28 22:29:15 WAST 2012
#~ Hit ENTER or wait ten seconds
#~ Tue Feb 28 22:29:25 WAST 2012
#~ wget -q --spider http://google.com
